# Generated by Django 5.2.15 on 2026-07-10 09:20

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='YogaRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('batch', models.CharField(choices=[('morning-6', 'Morning: 6:00 AM – 7:00 AM'), ('morning-7', 'Morning: 7:15 AM – 8:15 AM'), ('morning-8', 'Morning: 8:30 AM – 9:30 AM'), ('evening-6', 'Evening: 6:30 PM – 7:30 PM')], max_length=20)),
                ('registration_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('expiry_date', models.DateTimeField(blank=True, null=True)),
                ('booking_id', models.CharField(default=uuid.uuid4, editable=False, max_length=100, unique=True)),
                ('status', models.CharField(default='Pending', max_length=50)),
                ('agreed_to_terms', models.BooleanField(default=False)),
            ],
        ),
    ]
