# Generated by Django 5.2.15 on 2026-07-10 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yogaregistration',
            name='batch',
            field=models.CharField(choices=[('morning-600', 'Morning: 6:00 AM – 7:00 AM'), ('morning-715', 'Morning: 7:15 AM – 8:15 AM'), ('morning-830', 'Morning: 8:30 AM – 9:30 AM'), ('evening-630', 'Evening: 6:30 PM – 7:30 PM')], max_length=20),
        ),
    ]
