# Generated by Django 4.2.30 on 2026-09-14 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0002_alter_yogaregistration_batch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yogaregistration',
            name='batch',
            field=models.CharField(choices=[('morning-600', 'Morning: 6:00 AM – 7:00 AM'), ('morning-715', 'Morning: 7:15 AM – 8:15 AM'), ('morning-830', 'Morning: 8:30 AM – 9:30 AM'), ('morning-1030', 'Morning: 10:30 AM – 11:30 AM')], max_length=20),
        ),
    ]
