# Generated by Django 4.2.30 on 2026-09-27 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0003_alter_yogaregistration_batch'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthlyRenewal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=15)),
                ('batch', models.CharField(choices=[('morning-600', 'Morning: 6:00 AM – 7:00 AM'), ('morning-715', 'Morning: 7:15 AM – 8:15 AM'), ('morning-830', 'Morning: 8:30 AM – 9:30 AM'), ('morning-1030', 'Morning: 10:30 AM – 11:30 AM')], max_length=20)),
                ('renewal_month_number', models.IntegerField(default=2, help_text='e.g. 2 for 2nd Month, 3 for 3rd Month')),
                ('transaction_id', models.CharField(blank=True, help_text='UPI/GPay Reference ID', max_length=100, null=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(default='Pending Verification', max_length=50)),
            ],
        ),
    ]
