# Generated by Django 4.2.30 on 2026-09-27 06:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0004_monthlyrenewal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='monthlyrenewal',
            name='transaction_id',
        ),
    ]
