# Generated by Django 4.2.30 on 2026-09-27 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0005_remove_monthlyrenewal_transaction_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monthlyrenewal',
            name='renewal_month_number',
            field=models.CharField(default='2nd Month', max_length=50),
        ),
    ]
